### ISSUE TITLE
Phase change problem when using phase diagram

### ISSUE THREAD

**Issue by NicolasRiel** [UniMainzGeo/LaMEM#13]
Hello,

When trying to use phase change with phase diagram ("rho_ph" option in the Material  structure) we get the following error message. Without the phase diagram option "rho_ph" everything works fine.

```
 --------------------------------------------------------------------------
 ============================== INITIAL GUESS =============================
 --------------------------------------------------------------------------
 --------------------------------------------------------------------------
 **************   NONLINEAR SOLVER FAILED TO CONVERGE!   ****************** 
 --------------------------------------------------------------------------
 SNES Divergence Reason  : residual norm is NAN
 [0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
 [0]PETSC ERROR: Severe divergence reason detected (see above)
 [0]PETSC ERROR: WARNING! There are option(s) set that were not used! Could be the program crashed before they were used or a spelling mistake, etc!
 
```

This error message is obtained for instance using this in the input.dat file:

![Untitled-1](https://github.com/UniMainzGeo/LaMEM/assets/50235786/1895c55e-8d5e-4feb-991e-497c1199512a)

Nico

**Comment by NicolasRiel** [comment]
On the other hand, there is NaN in the phase diagram look-up-table. I might be the guilty one here...

**Comment by boriskaus** [comment]
Hmm, that is no good. We have no check in LaMEM for NaN‘s…

**Comment by NicolasRiel** [comment]
The issue has been fixed, it was coming from default "mfmax" not set to 1.0
